### ISSUE TITLE
License

### ISSUE THREAD

**Issue by epac-tom** [AqueronteBlog/ARM#117]
What license is in use for this project?
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

If the project is open to use could you please add the MIT license?

**Comment by AqueronteBlog** [comment]
All the code you can find here is open source

**Comment by amq** [comment]
Based on your comment I assume an MIT license, but I would be still extremely grateful if you could add it with a LICENSE file. This would make it possible to use your drivers in other projects.
